import argparse
import random
import shutil
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description="Stratified train/val split for OBB dataset")
    parser.add_argument("--images", "-i", type=str, required=True, help="Path to all images")
    parser.add_argument("--labels", "-l", type=str, required=True, help="Path to all labels")
    parser.add_argument("--output", "-o", type=str, default="../dataset", help="Output dataset root")
    parser.add_argument("--val-ratio", type=float, default=0.2, help="Validation ratio")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--copy", action="store_true", help="Copy instead of move")
    return parser.parse_args()


def main():
    args = parse_args()
    random.seed(args.seed)

    img_dir = Path(args.images)
    lbl_dir = Path(args.labels)
    out_dir = Path(args.output)

    if not img_dir.exists():
        print(f"[!] Image directory not found: {img_dir}")
        return
    if not lbl_dir.exists():
        print(f"[!] Label directory not found: {lbl_dir}")

    img_files = sorted(img_dir.glob("*.*"))
    print(f"[*] Found {len(img_files)} images in {img_dir}")

    image_label_pairs = []
    missing_labels = 0
    for img_path in img_files:
        lbl_path = lbl_dir / f"{img_path.stem}.txt"
        if lbl_path.exists():
            with open(lbl_path) as f:
                classes = set()
                for line in f:
                    parts = line.strip().split()
                    if parts:
                        classes.add(int(parts[0]))
            image_label_pairs.append((img_path, lbl_path, classes))
        else:
            missing_labels += 1

    if missing_labels:
        print(f"[!] {missing_labels} images missing labels (skipped)")

    if not image_label_pairs:
        print("[!] No valid image-label pairs found")
        return

    all_classes = set()
    for _, _, classes in image_label_pairs:
        all_classes.update(classes)
    all_classes = sorted(all_classes)

    stratified = {c: [] for c in all_classes}
    for img_path, lbl_path, classes in image_label_pairs:
        stratified[min(classes)].append((img_path, lbl_path, classes))

    train_pairs = []
    val_pairs = []

    for cls_id, pairs in stratified.items():
        random.shuffle(pairs)
        n_val = max(1, int(len(pairs) * args.val_ratio))
        val_pairs.extend(pairs[:n_val])
        train_pairs.extend(pairs[n_val:])

    if not train_pairs or not val_pairs:
        print("[!] Not enough samples for split, using random split")
        random.shuffle(image_label_pairs)
        n_val = max(1, int(len(image_label_pairs) * args.val_ratio))
        val_pairs = image_label_pairs[:n_val]
        train_pairs = image_label_pairs[n_val:]

    (out_dir / "train" / "images").mkdir(parents=True, exist_ok=True)
    (out_dir / "train" / "labels").mkdir(parents=True, exist_ok=True)
    (out_dir / "val" / "images").mkdir(parents=True, exist_ok=True)
    (out_dir / "val" / "labels").mkdir(parents=True, exist_ok=True)

    op = shutil.copy2 if args.copy else shutil.move
    op_name = "Copied" if args.copy else "Moved"

    for img_path, lbl_path, _ in train_pairs:
        op(str(img_path), str(out_dir / "train" / "images" / img_path.name))
        op(str(lbl_path), str(out_dir / "train" / "labels" / lbl_path.name))

    for img_path, lbl_path, _ in val_pairs:
        op(str(img_path), str(out_dir / "val" / "images" / img_path.name))
        op(str(lbl_path), str(out_dir / "val" / "labels" / lbl_path.name))

    train_classes = {}
    for _, _, classes in train_pairs:
        for c in classes:
            train_classes[c] = train_classes.get(c, 0) + 1
    val_classes = {}
    for _, _, classes in val_pairs:
        for c in classes:
            val_classes[c] = val_classes.get(c, 0) + 1

    out_yaml_path = out_dir / "dataset.yaml"
    names = {c: f"class_{c}" for c in all_classes}
    if len(all_classes) == 1:
        names[0] = "dial"

    yaml_content = f"""# Dataset YAML generated by data/split.py
path: {out_dir.resolve()}
train: train/images
val: val/images

nc: {len(all_classes)}
names: {names}
"""
    with open(out_yaml_path, "w") as f:
        f.write(yaml_content)

    print(f"\n{'='*50}")
    print(f"[+] Split complete!")
    print(f"    Train: {len(train_pairs)} images")
    print(f"    Val:   {len(val_pairs)} images")
    print(f"    Class distribution:")
    for c in all_classes:
        print(f"      Class {c}: {train_classes.get(c, 0)} train / {val_classes.get(c, 0)} val")
    print(f"    Dataset YAML: {out_yaml_path}")
    print(f"{'='*50}")


if __name__ == "__main__":
    main()
